### ISSUE TITLE
May have merge conflict when trying to pull changes

### ISSUE THREAD

**Issue by sagun-karki** [UNL-Hawkins-Lab/Hawkinslab#1]
There was an error with some routes, and I forcefully updated the main branch. You may get a problem pulling the changes.

I had an older website version, and I tried to pull it, but it pulled down. It may or may not be an issue.

**Comment by jfhawkin** [comment]
Sure. No problem.
________________________________
From: Sagun Karki ***@***.***>
Sent: Thursday, June 8, 2023 6:49 PM
To: UNL-Hawkins-Lab/Hawkinslab ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UNL-Hawkins-Lab/Hawkinslab] May have merge conflict when trying to pull changes (Issue #1)


There was an error with some routes, and I forcefully updated the main branch. You may get a problem pulling the changes.

I had an older website version, and I tried to pull it, but it pulled down. It may or may not be an issue.
